{
 "title": "Default Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "PV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Produktion",
   "type": "gauge",
   "description": "Eigenverbrauch heute",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Direkt verbraucht\" or r[\"_field\"] == \"PV Produktion\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Produktion",
   "type": "canvas",
   "description": "Eigenverbrauch heute",
   "gridPos": { "h": 11, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Direkt verbraucht\" or r[\"_field\"] == \"Energie ins Netz eingespeist\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "gauge",
   "description": "Autarkiegrad heute",
   "gridPos": { "h": 11, "w": 7, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PV Produktion\" or r[\"_field\"] == \"Verbrauch\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "canvas",
   "description": "Autarkiegrad heute",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PV Produktion\" or r[\"_field\"] == \"Energie vom Netz bezogen\" or r[\"_field\"] == \"Verbrauch\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Historie",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"topic\"] == \"pv\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Verbrauch\" or r[\"_field\"] == \"PV Produktion\" or r[\"_field\"] == \"Direkt verbraucht\" or r[\"_field\"] == \"State of Charge\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"State of Charge\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Produktion",
   "type": "canvas",
   "description": "Eigenverbrauch heute",
   "gridPos": { "h": 11, "w": 5, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Energie in Batterie gespeichert\" or r[\"_field\"] == \"Energie aus Batterie bezogen\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Historie",
   "type": "barchart",
   "description": "155 minutes equates to approximatly a month.",
   "gridPos": { "h": 19, "w": 11, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"topic\"] == \"pv\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Verbrauch\" or r[\"_field\"] == \"PV Produktion\" or r[\"_field\"] == \"Direkt verbraucht\")\r\n  |> aggregateWindow(every: 5m, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Sinus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sinus",
     "type": "timeseries",
     "description": "This is a sinus",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "query": "from(bucket: \"Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> aggregateWindow(every: 100ms, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}