CREATE TABLE "Kuenstler" (
	"KId" INTEGER NOT NULL UNIQUE,
	"Name" TEXT NOT NULL,
	"Gruendungsjahr" INTEGER,
	
	PRIMARY KEY("KId" AUTOINCREMENT)
);

CREATE TABLE "CD" (
	"CDId" INTEGER NOT NULL UNIQUE,
	"Albumtitel" TEXT NOT NULL,
	"IId" INTEGER NOT NULL,
	"Erscheinungsjahr" INTEGER,
	
	PRIMARY KEY("CDId" AUTOINCREMENT),
	FOREIGN KEY (IId) REFERENCES Kuenstler (KId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "Song" (
	"CDId" INTEGER NOT NULL,
	"Track" INTEGER NOT NULL,
	"Titel" TEXT NOT NULL,
	
	PRIMARY KEY("CDId","Track")
	FOREIGN KEY (CDId) REFERENCES CD (CDId) ON DELETE CASCADE ON UPDATE CASCADE
)